import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,componentName }) {
  console.log('componentName',componentName)
  return (
    <html lang="en">
      <body className="bg-indigo-600" >
        <Layout>{children} </Layout>
      </body>
    </html>
  );
}
